spring:
  application:
    name: djiankang
  cache:
    type: redis
    redis:
      time-to-live: 2592000000  # 30天缓存时间（单位：毫秒）
  servlet:
    multipart:
      # 允许文件上传
      enabled: true
      # 每个文件最大不能超过15MB
      max-file-size: 15MB
      # HTTP请求不能超过20MB，Spring MVC中的配置，属于二道防线。
      max-request-size: 20MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://82.156.211.164:3306/mnd-health?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: 123456
    hikari:
      # HikariCP不需要指定连接池初始大小，它会自动维护。
      # 最小空闲连接数
      minimum-idle: 8
      # 最大连接数
      maximum-pool-size: 16
      # 连接超时时间（毫秒）
      connection-timeout: 60000
      # 连接测试查询
      connection-test-query: SELECT 1
  data:
    mongodb:
      uri: mongodb://admin:123456@82.156.211.164:27017/mnd-health?authSource=admin
    redis:
      database: 0
      host: 82.156.211.164
      port: 6379
      password: 123456
      jedis:
        pool:
          #连接超时的最大时间
          max-active: 1000
          #等待空闲连接的最大等待时间（负数代表一直等待）
          max-wait: -1ms
          max-idle: 16
          min-idle: 8
minio:
  endpoint: http://82.156.211.164:9000
  access-key: root
  secret-key: 12345678
  bucket: mnd-health

server:
  port: 8080
  servlet:
    context-path: /api

  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: 123456


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: org.example.djiankang.db.entity
  configuration:
    #输出执行的SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
sa-token:
  # 在HTTP请求头（Header）中传递令牌时的name，例如发送请求时，这样提交token
  # const config = {headers: {'satoken': token}};
  # 为什么不采用cookie发送？为了更好地适配前后端分离、移动APP等非浏览器环境。
  token-name: satoken
  # Token 的长久有效期，设置为30天
  timeout: 2592000
  # 最低活跃频率有效期（-1表示没有最低活跃频率的限制）
  active-timeout: -1
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 设置为false时，Sa-Token 不会从 Cookie 中读取 Token，也不会自动将 Token 写入 Cookie
  # 设置为false，因为我们采用HTTP请求头提交
  is-read-cookie: false
  # 开启同端互斥(允许异端登录，但PC端只能有一个账号有效，或者移动端只能有一个账号有效)
  is-concurrent: true

knife4j:
  enable: true
  group:
    default:
      group-name: default
      api-rule: package
      api-rule-resources:
        - org.example.djiankang.front.controller
        - org.example.djiankang.mis.controller

logging:
  level:
    #SpringBoot日志级别
    root: info
    #MyBatis的日志级别
    org.example.djiankang.db.mapper: warn
  pattern:
    console: "%d{yyyy/MM/dd HH:mm:ss}  %-5level  %msg%n"